import { PartOfSpeech } from "../../types.js";
import { reverseObject } from "../../utils.js";

/**
 * @see https://en.wiktionary.org/wiki/Wiktionary:Entry_layout#Part_of_speech
 */
export default reverseObject({
	abbreviation: "Abbreviation",
	acronym: "Acronym",
	adjective: "Adjective",
	adposition: "Adposition",
	"adposition/ambiposition": "Ambiposition",
	"adposition/circumposition": "Circumposition",
	"adposition/postposition": "Postposition",
	"adposition/preposition": "Preposition",
	adverb: "Adverb",
	affix: "Affix",
	"affix/circumfix": "Circumfix",
	"affix/infix": "Infix",
	"affix/interfix": "Interfix",
	"affix/prefix": "Prefix",
	"affix/suffix": "Suffix",
	article: "Article",
	character: "Character",
	"character/han": "Han character",
	"character/hanzi": "Hanzi",
	"character/kanji": "Kanji",
	"character/hanja": "Hanja",
	classifier: "Classifier",
	clitic: "Clitic",
	conjunction: "Conjunction",
	contraction: "Contraction",
	counter: "Counter",
	determinative: "Determinative",
	determiner: "Determiner",
	"form/combining": "Combining form",
	gerund: "Gerund",
	ideophone: "Ideophone",
	idiom: "Idiom",
	initialism: "Initialism",
	interjection: "Interjection",
	letter: "Letter",
	ligature: "Ligature",
	logogram: "Logogram",
	"mark/diacritical": "Diacritical mark",
	"mark/punctuation": "Punctuation mark",
	noun: "Noun",
	"noun/proper": "Proper noun",
	number: "Number",
	numeral: "Numeral",
	"number/cardinal": "Cardinal number",
	"number/ordinal": "Ordinal number",
	"numeral/cardinal": "Cardinal numeral",
	"numeral/ordinal": "Ordinal numeral",
	participle: "Participle",
	particle: "Particle",
	phrase: "Phrase",
	"phrase/prepositional": "Prepositional phrase",
	pronoun: "Pronoun",
	proverb: "Proverb",
	romanization: "Romanization",
	root: "Root",
	syllable: "Syllable",
	symbol: "Symbol",
	verb: "Verb",
} satisfies Record<PartOfSpeech, string> as Record<PartOfSpeech, string>);
